services:
  # A web service for the FastAPI backend
  - type: web
    name: sales-forecast-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 8002
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: https://sales-forecasting-dashboard.netlify.app
      - key: GEMINI_API_KEY
        sync: false # This will be set manually in the Render dashboard
    autoDeploy: true
    healthCheckPath: /health
